### ISSUE TITLE
Dataproc java.lang.ClassNotFoundException: io.grpc.internal.BaseDnsNameResolverProvider

### ISSUE THREAD

**Issue by kanekotic** [googleapis/java-logging#276]
#### Environment details

1. Specify the API at the beginning of the title. For example, "BigQuery: ...").
   General, Core, and Other are also allowed as types
2. OS type and version: linux
3. Scala version: 2.12.10
4. logging version(s): 1.102.0

#### Steps to reproduce

try logging using library in dataproc environment with credentials in path

#### Code example

```scala
class GoogleLogger {
  val dateFormat = new SimpleDateFormat("yyyy-MM-dd")
  val config = Map(
    "run_date" -> dateFormat.format(new Date())
  )

  val credentials: GoogleCredentials = GoogleCredentials
    .fromStream(new FileInputStream("/some_path_to/credentials_file.json"))
    .createScoped(
      Lists.newArrayList("https://www.googleapis.com/auth/cloud-platform")
    )

  val logging: Logging =
    LoggingOptions
      .newBuilder()
      .setTransportOptions()
      .setCredentials(credentials)
      .build()
      .getService

  private def log(message: String, severity: Severity): Unit = {
    val entry = LogEntry
      .newBuilder(JsonPayload.of((config + ("msg" -> message)).asJava))
      .setSeverity(severity)
      .setLogName("bidderml-pipeline")
      .setResource(MonitoredResource.newBuilder("global").build)
      .build
    logging.write(Collections.singleton(entry))
  }

  def info(string: String): Unit = {
    log(string, Severity.INFO)
  }
...
}
```

#### Stack trace
```
Exception in thread "main" java.lang.NoClassDefFoundError: io/grpc/internal/BaseDnsNameResolverProvider
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:370)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at io.grpc.ServiceProviders.loadAll(ServiceProviders.java:67)
	at io.grpc.NameResolverRegistry.getDefaultRegistry(NameResolverRegistry.java:101)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.<init>(AbstractManagedChannelImplBuilder.java:107)
	at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder.<init>(NettyChannelBuilder.java:136)
	at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder.<init>(NettyChannelBuilder.java:131)
	at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder.forAddress(NettyChannelBuilder.java:117)
	at io.grpc.netty.shaded.io.grpc.netty.NettyChannelProvider.builderForAddress(NettyChannelProvider.java:37)
	at io.grpc.netty.shaded.io.grpc.netty.NettyChannelProvider.builderForAddress(NettyChannelProvider.java:23)
	at io.grpc.ManagedChannelBuilder.forAddress(ManagedChannelBuilder.java:39)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel(InstantiatingGrpcChannelProvider.java:270)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.access$1500(InstantiatingGrpcChannelProvider.java:71)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider$1.createSingleChannel(InstantiatingGrpcChannelProvider.java:202)
	at com.google.api.gax.grpc.ChannelPool.create(ChannelPool.java:72)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createChannel(InstantiatingGrpcChannelProvider.java:209)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.getTransportChannel(InstantiatingGrpcChannelProvider.java:192)
	at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:155)
	at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:122)
	at com.google.cloud.logging.spi.v2.GrpcLoggingRpc.<init>(GrpcLoggingRpc.java:132)
	at com.google.cloud.logging.LoggingOptions$DefaultLoggingRpcFactory.create(LoggingOptions.java:61)
	at com.google.cloud.logging.LoggingOptions$DefaultLoggingRpcFactory.create(LoggingOptions.java:55)
	at com.google.cloud.ServiceOptions.getRpc(ServiceOptions.java:561)
	at com.google.cloud.logging.LoggingOptions.getLoggingRpcV2(LoggingOptions.java:129)
	at com.google.cloud.logging.LoggingImpl.<init>(LoggingImpl.java:109)
	at com.google.cloud.logging.LoggingOptions$DefaultLoggingFactory.create(LoggingOptions.java:46)
	at com.google.cloud.logging.LoggingOptions$DefaultLoggingFactory.create(LoggingOptions.java:41)
	at com.google.cloud.ServiceOptions.getService(ServiceOptions.java:541)
	at com.chartboost.bidderml.helpers.GoogleLogger.<init>(Logger.scala:38)
	at com.chartboost.bidderml.configuration.modules.providers.LoggerProvider.get(LoggerProvider.scala:10)
	at com.chartboost.bidderml.configuration.modules.providers.LoggerProvider.get(LoggerProvider.scala:7)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
	at com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:72)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)
	at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:62)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:104)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1047)
	at net.codingwell.scalaguice.InjectorExtensions$ScalaInjector$.instance$extension0(InjectorExtensions.scala:27)
	at com.chartboost.bidderml.app$.main(app.scala:22)
	at com.chartboost.bidderml.app.main(app.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:928)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1007)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1016)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.ClassNotFoundException: io.grpc.internal.BaseDnsNameResolverProvider
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 83 more
```

#### Any additional information below

Following these steps guarantees the quickest resolution possible.

Thanks!

**Comment by athakor** [comment]
Thanks @kanekotic, I was able to reproduce this issue by running the above sample with `scala(sbt)`. It looks like when we upgraded to `grpc v1.29.0` in this release, `io.grpc.internal.DnsNameResolverProvider.enable_grpclb` was removed in this version: https://github.com/grpc/grpc-java/releases/tag/v1.29.0 

Looking at dependencies, `gax (version 1.56.0)` depends on `grpc-alts 1.28.1`,which is why we are seeing this issue. Forcing the `io.grpc:grpc-alts` to `1.29.0` seems to resolve the issue.

**build.sbt :**

```sbt
libraryDependencies += "com.google.cloud" % "google-cloud-logging" % "1.102.0" exclude("io.grpc", "grpc-alts")

libraryDependencies += "io.grpc" % "grpc-alts" % "1.29.0"
```

**Comment by athakor** [comment]
@kanekotic does above comment works on your end? if _`YES`_ then can we closed this issue?

**Comment by kanekotic** [comment]
yes it worked @athakor. Nevertheless it seems like a workaround for a very straight forward dependency. So I would recomend for google to solve this as it seems to be a real bug.

**Comment by athakor** [comment]
> yes it worked @athakor. Nevertheless it seems like a workaround for a very straight forward dependency. So I would recomend for google to solve this as it seems to be a real bug.

cc: @chingor13

**Comment by simonz130** [comment]
We're at java logging 2.2.0 now - I'm closing this as it seems obsolete. Let me know if you encounter this in the newest java package.
