### ISSUE TITLE
Stackdriver Java integration throwing - LoggingException: io.grpc.StatusRuntimeException: UNAVAILABLE: HTTP/2 error code: NO_ERROR Received Goaway 

### ISSUE THREAD

**Issue by ayushj158** [googleapis/java-logging#35]
We are using Cloud logging java integration. Our application is not hosted on google cloud but sends logs to stack driver and also has monitoring alerts there. 

Intermittently we are seeing below exception logs in stack trace. At times application is able to recover from it and sometimes it is not ,as a consequence no more logs are sent to stack-driver . 

We cannot afford such situation in our production system, i would like to understand what the root cause behind this and if we have a possible solution

#### Environment details

- OS: Linus
- Java version: 8
- google-cloud-logging version(s): 1.50

#### Stacktrace

```
stacktrace:  "java.lang.RuntimeException: com.google.cloud.logging.LoggingException: io.grpc.StatusRuntimeException: UNAVAILABLE: HTTP/2 error code: NO_ERROR
Received Goaway
session_timed_out
  at com.google.cloud.logging.LoggingImpl$7.onFailure(LoggingImpl.java:578)
  at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:68)
  at com.google.common.util.concurrent.Futures$4.run(Futures.java:1123)
  at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435)
  at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:900)
  at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:811)
  at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:675)
  at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:112)
  at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435)
  at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:900)
  at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:811)
  at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:675)
  at com.google.common.util.concurrent.AbstractCatchingFuture.run(AbstractCatchingFuture.java:134)
  at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435)
  at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:900)
  at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:811)
  at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:675)
  at com.google.api.core.AbstractApiFuture$InternalSettableFuture.setException(AbstractApiFuture.java:95)
  at com.google.api.core.AbstractApiFuture.setException(AbstractApiFuture.java:77)
  at com.google.api.gax.rpc.BatchedFuture.setException(BatchedFuture.java:55)
  at com.google.api.gax.rpc.BatchedRequestIssuer.sendResult(BatchedRequestIssuer.java:84)
  at com.google.api.gax.rpc.BatchExecutor$1.onFailure(BatchExecutor.java:98)
  at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:68)
  at com.google.common.util.concurrent.Futures$4.run(Futures.java:1123)
  at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435)
  at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:900)
  at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:811)
  at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:675)
  at com.google.api.core.AbstractApiFuture$InternalSettableFuture.setException(AbstractApiFuture.java:95)
  at com.google.api.core.AbstractApiFuture.setException(AbstractApiFuture.java:77)
  at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97)
  at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:68)
  at com.google.common.util.concurrent.Futures$4.run(Futures.java:1123)
  at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435)
  at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:900)
  at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:811)
  at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:675)
  at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:507)
  at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:482)
  at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
  at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
  at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
  at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:678)
  at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
  at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
  at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
  at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:403)
  at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
  at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
  at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
  at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
  at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
  at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
  at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at java.lang.Thread.run(Thread.java:748)
```

#### Code snippet

```java
We are using an custom StackdriverAppender and not OOB Logging appendor
```
#### Logback-xml
```LogbackXML
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
     <!--console logs appender  -->
     <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <layout class="ch.qos.logback.classic.PatternLayout">
            <Pattern>
                %d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
            </Pattern>
        </layout>
    </appender>

    <!--Stack driver appender-->
    <appender name="STACKDRIVER" class="com.kramphub.log.StackdriverAppender">
        <layout class="ch.qos.logback.classic.PatternLayout">
            <Pattern>
                %logger{36} - %msg %nopex
            </Pattern>
        </layout>
        <logName>datapump</logName>
    </appender>
    <root level="INFO">
    	<appender-ref ref="STDOUT"/>
        <appender-ref ref="STACKDRIVER"/>
    </root>
</configuration>
```
Thanks!

**Comment by minherz** [comment]
@ayushj158  do you still get these errors?
