### ISSUE TITLE
ITLoggingTest is broken on kokoro

### ISSUE THREAD

**Issue by elharo** [googleapis/java-logging#430]
java.lang.AssertionError:
expected:<StringPayload{type=STRING, data=stringPayload}> but was:<JsonPayload{type=JSON, data=fields {
  key: "jsonKey"
  value {
    string_value: "jsonValue"
  }
}
}>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:120)
	at org.junit.Assert.assertEquals(Assert.java:146)
	at com.google.cloud.logging.it.ITLoggingTest.testListEntries(ITLoggingTest.java:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)

**Comment by Daniel-Sanche** [comment]
I believe this was fixed in a PR a couple weeks ago: https://github.com/googleapis/java-logging/pull/425

I'm seeing the integration tests passing on recent runs, but let me know if you think it's still an issue and I can take another look
