### ISSUE TITLE
java.lang.RuntimeException: ManagedChannel allocation site

### ISSUE THREAD

**Issue by shuZro** [googleapis/java-logging#76]
```
*~*~*~ Channel ManagedChannelImpl{logId=1, target=logging.googleapis.com:443} was not shutdown properly!!! ~*~*~*
    Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
java.lang.RuntimeException: ManagedChannel allocation site
	at io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference.<init>(ManagedChannelOrphanWrapper.java:94)
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:52)
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:43)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:524)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel(InstantiatingGrpcChannelProvider.java:296)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createChannel(InstantiatingGrpcChannelProvider.java:194)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.getTransportChannel(InstantiatingGrpcChannelProvider.java:186)
	at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:155)
	at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:122)
	at com.google.cloud.logging.spi.v2.GrpcLoggingRpc.<init>(GrpcLoggingRpc.java:132)
*~*~*~ Channel ManagedChannelImpl{logId=9, target=logging.googleapis.com:443} was not shutdown properly!!! ~*~*~*
    Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
java.lang.RuntimeException: ManagedChannel allocation site
	at io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference.<init>(ManagedChannelOrphanWrapper.java:94)
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:52)
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:43)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:524)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel(InstantiatingGrpcChannelProvider.java:296)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createChannel(InstantiatingGrpcChannelProvider.java:194)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.getTransportChannel(InstantiatingGrpcChannelProvider.java:186)
	at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:155)
	at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:122)
	at com.google.cloud.logging.spi.v2.GrpcLoggingRpc.<init>(GrpcLoggingRpc.java:132)
```

**Comment by pmakani** [comment]
@shuZro please share you example here.

**Comment by shuZro** [comment]
i am just calling LoggingOptions.getDefaultInstance

then logging = options.getService
and logging.listLogEntries(
        EntryListOption.filter(filter)
      )
and then iterating

the first time i run these its fine but i call the them again i get the java.lang.RuntimeException as shown above. i still get correct results but just wondering what this error is.

**Comment by pmakani** [comment]
@ShuZro Logging client has two types of transportation layer.
1. for Rest client
 ```Java
   Logging logging = LoggingOptions.getOptions().getService();
   logging.listLogEntries(EntryListOption.filter(filter)
```
2. for GRPC client
  ```JAVA
   LoggingClient loggingClient = LoggingClient.create();
   ListLogEntriesRequest request = ListLogEntriesRequest.newBuilder()
   	.addAllResourceNames(ParentName.toStringList(resourceNames))
   	.build();
   loggingClient.listLogEntries(loggingClient);
```
so you are using Rest client but that error is related to GRPC client.
i am wondering how did you receive that error so investigating it.

**Comment by ivanzhujunwei** [comment]
Hi, I am also having this issue, I am following this guide. https://cloud.google.com/logging/docs/reference/libraries

Can someone help?

> io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference cleanQueue: *~*~*~ Channel ManagedChannelImpl{logId=29, target=logging.googleapis.com:443} was not shutdown properly!!! ~*~*~*
>     Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
> java.lang.RuntimeException: ManagedChannel allocation site
> 	at io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference.<init>(ManagedChannelOrphanWrapper.java:93)
> 	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:53)
> 	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:44)
> 	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:517)
> 	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel(InstantiatingGrpcChannelProvider.java:314)
> 	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.access$1600(InstantiatingGrpcChannelProvider.java:71)
> 	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider$1.createSingleChannel(InstantiatingGrpcChannelProvider.java:210)
> 	at com.google.api.gax.grpc.ChannelPool.create(ChannelPool.java:72)
> 	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createChannel(InstantiatingGrpcChannelProvider.java:217)
> 	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.getTransportChannel(InstantiatingGrpcChannelProvider.java:200)
> 	at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:156)
> 	at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:123)
> 	at com.google.cloud.logging.spi.v2.GrpcLoggingRpc.<init>(GrpcLoggingRpc.java:132)
> 	at com.google.cloud.logging.LoggingOptions$DefaultLoggingRpcFactory.create(LoggingOptions.java:61)
> 	at com.google.cloud.logging.LoggingOptions$DefaultLoggingRpcFactory.create(LoggingOptions.java:55)
> 	at com.google.cloud.ServiceOptions.getRpc(ServiceOptions.java:561)
> 	at com.google.cloud.logging.LoggingOptions.getLoggingRpcV2(LoggingOptions.java:129)
> 	at com.google.cloud.logging.LoggingImpl.<init>(LoggingImpl.java:87)
> 	at com.google.cloud.logging.LoggingOptions$DefaultLoggingFactory.create(LoggingOptions.java:46)
> 	at com.google.cloud.logging.LoggingOptions$DefaultLoggingFactory.create(LoggingOptions.java:41)
> 	at com.google.cloud.ServiceOptions.getService(ServiceOptions.java:541)

**Comment by ivanzhujunwei** [comment]
Hi, in order to avoid the issue, my way is to close the resource which is cloud logging in this case. 
`// Instantiates a client
    Logging logging = LoggingOptions.getDefaultInstance().getService();`

There are two ways to close the resource:

1. Directly use the close() function  --> `logging.close();`
2. Use try-with-resource block -->
   `try( Logging logging = LoggingOptions.getDefaultInstance().getService() ){...}`
    The try-with-resources statement ensures that each resource is closed at the end of the statement.

**Comment by suraj-qlogic** [comment]
@shuZro ,@ivanzhujunwei ,This is fixed in [java-logging-211](https://github.com/googleapis/java-logging/issues/211)

**Comment by ivanzhujunwei** [comment]
Hi @suraj-qlogic  does that mean the Logging resource does not need to be closed after the fix you mentioned? At the moment, if the Logging resource is closed, then this error won't happen. Please correct me if I am wrong, thanks!

**Comment by ivanzhujunwei** [comment]
Ok, had a quick look about your fix in java-logging-211, the resource is closed inside the library, am I right? Thanks!

**Comment by suraj-qlogic** [comment]
@ivanzhujunwei ,

> Ok, had a quick look about your fix in java-logging-211, the resource is closed inside the library, am I right? Thanks! @suraj-qlogic

yes right
