### ISSUE TITLE
Java-Logging API: Retrieving logentries pagewise always results in an exception

### ISSUE THREAD

**Issue by mwolff-bay** [googleapis/java-logging#987]
OS-Type: MacOS Darwin 21.5.0
Java-Version: openjdk version "1.8.0_322"

Hi folks,
please find attached a small demo for creating and retrieving logentries (a readme is included).
Whenever I try to iterate over the first page of retrieved logentries I get the following exception:

Exception in thread "main" com.google.cloud.logging.LoggingException: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: page_token doesn't match arguments from the request
	at com.google.cloud.logging.spi.v2.GrpcLoggingRpc$2.apply(GrpcLoggingRpc.java:208)
	at com.google.cloud.logging.spi.v2.GrpcLoggingRpc$2.apply(GrpcLoggingRpc.java:202)
	at com.google.api.core.ApiFutures$ApiFunctionToGuavaFunction.apply(ApiFutures.java:239)
	at com.google.common.util.concurrent.AbstractCatchingFuture$CatchingFuture.doFallback(AbstractCatchingFuture.java:234)
	at com.google.common.util.concurrent.AbstractCatchingFuture$CatchingFuture.doFallback(AbstractCatchingFuture.java:222)
	at com.google.common.util.concurrent.AbstractCatchingFuture.run(AbstractCatchingFuture.java:133)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1270)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:1038)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:808)
	at com.google.api.gax.retrying.BasicRetryingFuture.handleAttempt(BasicRetryingFuture.java:200)
	at com.google.api.gax.retrying.CallbackChainRetryingFuture$AttemptCompletionListener.handle(CallbackChainRetryingFuture.java:135)
	at com.google.api.gax.retrying.CallbackChainRetryingFuture$AttemptCompletionListener.run(CallbackChainRetryingFuture.java:117)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1270)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:1038)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:808)
	at com.google.api.core.AbstractApiFuture$InternalSettableFuture.setException(AbstractApiFuture.java:94)
	at com.google.api.core.AbstractApiFuture.setException(AbstractApiFuture.java:76)
	at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97)
	at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:67)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1132)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1270)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:1038)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:808)
	at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:563)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:533)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at com.google.api.gax.grpc.ChannelPool$ReleasingClientCall$1.onClose(ChannelPool.java:535)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:562)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:743)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:722)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: com.google.api.gax.rpc.InvalidArgumentException: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: page_token doesn't match arguments from the request
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:92)
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:41)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:86)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:66)
	... 22 more
Caused by: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: page_token doesn't match arguments from the request
	at io.grpc.Status.asRuntimeException(Status.java:535)
	... 14 more

From my perspective it seems so, that the API implementation has some kind of bug.

Regards,
Michael

[logging-demo.tgz](https://github.com/googleapis/java-logging/files/9038880/logging-demo.tgz)

**Comment by coelhodeoliveira** [comment]
I also have the same issue. I did some tests here and also found the same problem.

**Comment by coelhodeoliveira** [comment]
I even tried to rollback the lib version to `2.3.1`. The error persists.

**Comment by wudstrand** [comment]
I am seeing the same issue.

**Comment by losalex** [comment]
@mwolff-bay, thanks a lot for filing the issue and for great demo! I am adding this to a queue and will update on a progress

**Comment by mwolff-bay** [comment]
> @mwolff-bay, thanks a lot for filing the issue and for great demo! I am adding this to a queue and will update on a progress

Great job, thx. a lot for the investigative work and the explanation what I did wrong.

**Comment by losalex** [comment]
> > @mwolff-bay, thanks a lot for filing the issue and for great demo! I am adding this to a queue and will update on a progress
> 
> Great job, thx. a lot for the investigative work and the explanation what I did wrong.

@mwolff-bay , I believe you didn't do anything wrong and your code is completely valid - I sent PR already to fix this issue in a library. If you need to workaround the problem as of right now, you can try setting `EntryListOption.FILTER` explicitly in your code by including `timestamp` parameter in filter (e.g. for example filter for last 24 hours is `timestamp>="2022-12-05T20:13:23.212Z"`) - I believe this should help of mitigating an issue. Please let me know if I can help with anything else.

**Comment by losalex** [comment]
@mwolff-bay / @coelhodeoliveira - I tried the fix with latest library and it worked for me, so if you can try it to see if it works for you I would really appreciate your help

**Comment by mwolff-bay** [comment]
> @mwolff-bay / @coelhodeoliveira - I tried the fix with latest library and it worked for me, so if you can try it to see if it works for you I would really appreciate your help

Exception has gone, well done - everything works fine now.
